# Generated by Django 5.2.5 on 2025-08-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='notes/storage/'),
        ),
    ]
